import 'server-only'
import fs from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import readingTime from 'reading-time'

// File-system blog source. Posts live as markdown with frontmatter in
// content/blog/ (generated by scripts/generate-blog.mjs). Parsed once and
// cached per server process.

const BLOG_DIR = path.join(process.cwd(), 'content', 'blog')

export type PostMeta = {
  slug: string
  title: string
  date: string
  category: string
  excerpt: string
  tags: string[]
  author: string
  readingMinutes: number
}

export type Post = PostMeta & { content: string }

let cache: Post[] | null = null

function loadAll(): Post[] {
  if (cache) return cache
  if (!fs.existsSync(BLOG_DIR)) {
    cache = []
    return cache
  }
  const files = fs.readdirSync(BLOG_DIR).filter((f) => f.endsWith('.md'))
  const posts = files.map((file) => {
    const raw = fs.readFileSync(path.join(BLOG_DIR, file), 'utf8')
    const { data, content } = matter(raw)
    return {
      slug: data.slug || file.replace(/\.md$/, ''),
      title: data.title,
      date: data.date,
      category: data.category,
      excerpt: data.excerpt,
      tags: data.tags || [],
      author: data.author,
      readingMinutes: Math.max(1, Math.round(readingTime(content).minutes)),
      content,
    } as Post
  })
  posts.sort((a, b) => (a.date < b.date ? 1 : -1))
  cache = posts
  return posts
}

export function getAllPostMeta(): PostMeta[] {
  return loadAll().map(({ content: _content, ...meta }) => meta)
}

export function getPostBySlug(slug: string): Post | null {
  return loadAll().find((p) => p.slug === slug) ?? null
}

export function getAllSlugs(): string[] {
  return loadAll().map((p) => p.slug)
}

export function getCategories(): Array<{ name: string; count: number }> {
  const counts = new Map<string, number>()
  for (const p of loadAll()) {
    counts.set(p.category, (counts.get(p.category) ?? 0) + 1)
  }
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count)
}
